apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-quarkus
  namespace: todo-nguennemann
spec:
  paused: true
  selector:
    matchLabels:
      app: httpd
  replicas: 3
  template:
    metadata:
      labels:
        app: todo-api-quarkus
    spec:
      serviceAccountName: todo-api-quarkus
      containers:
        - name: todo-api-quarkus
          image:
            kind: ImageStreamTag
            name: todo-api-quarkus:latestt
          ports:
            - containerPort: 8080
