apiVersion: v1
kind: Service
type: ClusterIP
metadata:
  name: todo-api-quarkus
spec:
  selector:
    app: todo-api-quarkus
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080